In [1462]:
import pandas as pd
from sklearn.model_selection import train_test_split,  GridSearchCV
from sklearn.preprocessing import StandardScaler , MinMaxScaler , OneHotEncoder, PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error

df = pd.read_csv('ToyotaCorolla.csv')

## Датасет:

In [1463]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   str
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   str
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   str
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), str(3)
memory usage: 437.7 KB

In [1464]:
df.describe()

                Id         Price  ...  Parking_Assistant      Tow_Bar
count  1436.000000   1436.000000  ...        1436.000000  1436.000000
mean    721.555014  10730.824513  ...           0.002786     0.277855
std     416.476890   3626.964585  ...           0.052723     0.448098
min       1.000000   4350.000000  ...           0.000000     0.000000
25%     361.750000   8450.000000  ...           0.000000     0.000000
50%     721.500000   9900.000000  ...           0.000000     0.000000
75%    1081.250000  11950.000000  ...           0.000000     1.000000
max    1442.000000  32500.000000  ...           1.000000     1.000000

[8 rows x 36 columns]

In [1465]:
df.describe(include='str')

                                                    Model Fuel_Type Color
count                                                1436      1436  1436
unique                                                319         3    10
top     TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...    Petrol  Grey
freq                                                  109      1264   301

In [1466]:
NaN = df.isnull().sum().value_counts()
print(NaN)

0    39
Name: count, dtype: int64

## Предобработка: удаление скоррелированых/не нужных для поставленной задачи данных

In [1467]:
# корелляция между циллиндрами и объемом

print(df['Cylinders'].corr(df['CC']))

nan

/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

1) Cylinders содержит единственное значение 4, значит удаляем

In [1468]:
# корелляция между передачами и объемом

print(df['Gears'].corr(df['CC']))

0.014629352089597158

### Итак, ненужными/бесполезными я счел следующие признаки: 
 - Cylinders - единственное значение
 - Weight - несущественный показатель
 - Backseat_Divider - не существенный показатель
 - Tow_Bar - несущественный показатель
 - Radio_cassette - несущественный (устаревший) показатель
 - CD_Player - несущественный (устаревший) показатель
 - Met_Color - несущественный (устаревший) показатель
 - Metallic_Rim - несущественный (устаревший) показатель
 - Mistlamps - несущественный (устаревший) показатель
 - Model - содержит слишком много значений

In [1469]:

cols_to_drop = [
    'Cylinders',
    'Weight',
    'Backseat_Divider',
    'Tow_Bar',
    'Radio_cassette',
    'CD_Player',
    'Met_Color',
    'Metallic_Rim',
    'Mistlamps',
    'Model'
]

df = df.drop(columns=cols_to_drop)

## Feature Ingeneering

### Создам 1 колонку с возрастом вместо 3 разных

In [1470]:
base_year = 2004
base_month = 8
df['Age_Month'] = (base_year*12 + base_month) - df['Mfg_Year']*12 + df['Mfg_Month'] + df['Age_08_04']

df = df.drop(columns=['Mfg_Year', 'Mfg_Month', 'Age_08_04'])

In [1471]:
print(df['Age_Month'].corr(df['KM']))

0.5049744502001694

### One-hot encoding для оставшихся str признаков

In [1472]:
df = pd.get_dummies(df, columns=['Fuel_Type'], prefix='Fuel', drop_first=True)

In [1473]:
print(df['Color'].value_counts())

Color
Grey      301
Blue      283
Red       278
Green     220
Black     191
Silver    122
White      31
Violet      4
Yellow      3
Beige       3
Name: count, dtype: int64

In [1474]:
df['Color'] = df['Color'].apply(lambda x: 'Other' if x in ['Violet', 'Yellow', 'Beige'] else x)

df = pd.get_dummies(df, columns=['Color'], prefix='Color')
df = df.drop(columns='Color_Other')

In [1475]:
df.info()
df.describe(include=['int64', 'bool'])

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 34 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Price              1436 non-null   int64
 2   KM                 1436 non-null   int64
 3   HP                 1436 non-null   int64
 4   Automatic          1436 non-null   int64
 5   CC                 1436 non-null   int64
 6   Doors              1436 non-null   int64
 7   Gears              1436 non-null   int64
 8   Quarterly_Tax      1436 non-null   int64
 9   Mfr_Guarantee      1436 non-null   int64
 10  BOVAG_Guarantee    1436 non-null   int64
 11  Guarantee_Period   1436 non-null   int64
 12  ABS                1436 non-null   int64
 13  Airbag_1           1436 non-null   int64
 14  Airbag_2           1436 non-null   int64
 15  Airco              1436 non-null   int64
 16  Automatic_airco    1436 non-null   int64
 17  Boardcomputer      1436 non-null   int64
 18  Central_Lock       1436 non-null   int64
 19  Powered_Windows    1436 non-null   int64
 20  Power_Steering     1436 non-null   int64
 21  Radio              1436 non-null   int64
 22  Sport_Model        1436 non-null   int64
 23  Parking_Assistant  1436 non-null   int64
 24  Age_Month          1436 non-null   int64
 25  Fuel_Diesel        1436 non-null   bool
 26  Fuel_Petrol        1436 non-null   bool
 27  Color_Black        1436 non-null   bool
 28  Color_Blue         1436 non-null   bool
 29  Color_Green        1436 non-null   bool
 30  Color_Grey         1436 non-null   bool
 31  Color_Red          1436 non-null   bool
 32  Color_Silver       1436 non-null   bool
 33  Color_White        1436 non-null   bool
dtypes: bool(9), int64(25)
memory usage: 293.2 KB

                 Id         Price  ...  Color_Silver  Color_White
count   1436.000000   1436.000000  ...          1436         1436
unique          NaN           NaN  ...             2            2
top             NaN           NaN  ...         False        False
freq            NaN           NaN  ...          1314         1405
mean     721.555014  10730.824513  ...           NaN          NaN
std      416.476890   3626.964585  ...           NaN          NaN
min        1.000000   4350.000000  ...           NaN          NaN
25%      361.750000   8450.000000  ...           NaN          NaN
50%      721.500000   9900.000000  ...           NaN          NaN
75%     1081.250000  11950.000000  ...           NaN          NaN
max     1442.000000  32500.000000  ...           NaN          NaN

[11 rows x 34 columns]

## Разделение выборки данных

In [1476]:
df_X = df.drop(columns='Price')
df_Y = df['Price']

x_train, x_test, y_train, y_test = train_test_split(df_X, df_Y, test_size=0.3, random_state=42)

### Я решил разделить выборку в соотношении 70/30, ибо данных для обучения достаточно, и есть смысл оставить побольше для проверки.

### разделение данных на такие выборки нужно, ибо модель так или иначе подстраивается под данные, на которых она учится, поэтому проверка ее качества на данных, которых она училась необъективна и может привести к переобучению

## Обучение модели

In [1477]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [1478]:
model = LinearRegression()

model.fit(x_train, y_train)

y_pred_train = model.predict(x_train)
y_pred = model.predict(x_test)


mse_train = mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)
mape_train = mean_absolute_percentage_error(y_train, y_pred_train)

mse_test = mean_squared_error(y_test, y_pred)
r2_test = r2_score(y_test, y_pred)
mape_test = mean_absolute_percentage_error(y_test, y_pred)

print(f'MSE train: {mse_train}')
print(f'R^2 train: {r2_train}')
print(f'MAPE train: {mape_train}')

print(f'MSE test: {mse_test}')
print(f'R^2 test: {r2_test}')
print(f'MAPE test: {mape_test}')

MSE train: 1224078.6657567555
R^2 train: 0.9044638542804233
MAPE train: 0.08287717973147422
MSE test: 1313850.4457755554
R^2 test: 0.905628708603394
MAPE test: 0.08524833847703835

#### вроде нормально и так, но я попробую, что будет для регуляризации

In [1479]:
ridge = Ridge()

ridge.fit(x_train, y_train)

y_pred_train = ridge.predict(x_train)
y_pred = ridge.predict(x_test)


mse_train = mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)
mape_train = mean_absolute_percentage_error(y_train, y_pred_train)

mse_test = mean_squared_error(y_test, y_pred)
r2_test = r2_score(y_test, y_pred)
mape_test = mean_absolute_percentage_error(y_test, y_pred)

print(f'MSE train: {mse_train}')
print(f'R^2 train: {r2_train}')
print(f'MAPE train: {mape_train}')

print(f'MSE test: {mse_test}')
print(f'R^2 test: {r2_test}')
print(f'MAPE test: {mape_test}')

MSE train: 1224295.0461629217
R^2 train: 0.9044469663543507
MAPE train: 0.08283351695217811
MSE test: 1315804.0266760157
R^2 test: 0.9054883867326536
MAPE test: 0.08521894793570403

In [1480]:
lasso = Lasso()

lasso.fit(x_train, y_train)

y_pred_train = lasso.predict(x_train)
y_pred = lasso.predict(x_test)


mse_train = mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)
mape_train = mean_absolute_percentage_error(y_train, y_pred_train)

mse_test = mean_squared_error(y_test, y_pred)
r2_test = r2_score(y_test, y_pred)
mape_test = mean_absolute_percentage_error(y_test, y_pred)

print(f'MSE train: {mse_train}')
print(f'R^2 train: {r2_train}')
print(f'MAPE train: {mape_train}')

print(f'MSE test: {mse_test}')
print(f'R^2 test: {r2_test}')
print(f'MAPE test: {mape_test}')

MSE train: 1224252.5789315153
R^2 train: 0.9044502808109469
MAPE train: 0.08284630291381033
MSE test: 1316556.2775436996
R^2 test: 0.9054343540335243
MAPE test: 0.08525450135678891

In [1481]:
# перед этим я дропну еще признаков, ибо PolynomialFeatures даже для deg = 2 добавит еще С(34, 2) = 34*33/(2!) признаков
# spoiler: это ухудшило качество, поэтому я попробую приемнить для текущего датасета

steps = [
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Lasso(max_iter=100))
]
pipe = Pipeline(steps)

# + небольшой поиск руками
param_grid = {'model__alpha': [0.01, 0.1, 1.0, 30.0, 100.0]}
grid = GridSearchCV(pipe, param_grid, cv=5, scoring='r2')
grid.fit(x_train, y_train)

best = grid.best_estimator_
print(f"Best param: {grid.best_params_['model__alpha']}")

y_pred_lasso_train = best.predict(x_train)
y_pred_lasso = best.predict(x_test)

r2_train = r2_score(y_train, y_pred_lasso_train)
mape_lasso_train = mean_absolute_percentage_error(y_train, y_pred_lasso_train)
r2 = r2_score(y_test, y_pred_lasso)
mape_lasso = mean_absolute_percentage_error(y_test, y_pred_lasso)

print(f"R^2 train: {r2_train}")
print(f"R^2 test: {r2}")
print(f"MAPE train: {mape_lasso_train}")
print(f"MAPE test: {mape_lasso}")

/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.625e+08, tolerance: 1.083e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.477e+08, tolerance: 9.757e+05
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.584e+08, tolerance: 1.026e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.583e+08, tolerance: 1.004e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.651e+08, tolerance: 1.059e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.657e+08, tolerance: 1.083e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.501e+08, tolerance: 9.757e+05
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.617e+08, tolerance: 1.026e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.616e+08, tolerance: 1.004e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.667e+08, tolerance: 1.059e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.584e+08, tolerance: 1.083e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.468e+08, tolerance: 9.757e+05
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.717e+08, tolerance: 1.026e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.577e+08, tolerance: 1.004e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.651e+08, tolerance: 1.059e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.848e+07, tolerance: 1.083e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.807e+07, tolerance: 9.757e+05
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.198e+07, tolerance: 1.026e+06
  model = cd_fast.enet_coordinate_descent(

Best param: 30.0
R^2 train: 0.9379350082098635
R^2 test: 0.9227168994414096
MAPE train: 0.06770540657248877
MAPE test: 0.08091529605517175

/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.865e+07, tolerance: 1.004e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.142e+07, tolerance: 1.059e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.814e+07, tolerance: 1.083e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.182e+06, tolerance: 9.757e+05
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.939e+07, tolerance: 1.026e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.718e+07, tolerance: 1.004e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.142e+07, tolerance: 1.059e+06
  model = cd_fast.enet_coordinate_descent(
/Users/alex/Desktop/ml-course-homeworks/.venv/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.179e+07, tolerance: 1.288e+06
  model = cd_fast.enet_coordinate_descent(

In [ ]:
# и для ridge

steps = [
    ('poly', PolynomialFeatures(degree=2)),
    ('model', Ridge(max_iter=100))
]
pipe = Pipeline(steps)

# + небольшой поиск руками
param_grid = {'model__alpha': [0.01, 0.1, 1.0, 30.0, 100.0]}
grid = GridSearchCV(pipe, param_grid, cv=5, scoring='r2')
grid.fit(x_train, y_train)

best = grid.best_estimator_
print(f"Best param: {grid.best_params_['model__alpha']}")

y_pred_lasso_train = best.predict(x_train)
y_pred_lasso = best.predict(x_test)

r2_train = r2_score(y_train, y_pred_lasso_train)
mape_lasso_train = mean_absolute_percentage_error(y_train, y_pred_lasso_train)
r2 = r2_score(y_test, y_pred_lasso)
mape_lasso = mean_absolute_percentage_error(y_test, y_pred_lasso)

print(f"R^2 train: {r2_train}")
print(f"R^2 test: {r2}")
print(f"MAPE train: {mape_lasso_train}")
print(f"MAPE test: {mape_lasso}")

Best param: 30.0
R^2 train: 0.9604599407552212
R^2 test: 0.8754593127749503
MAPE train: 0.05345756283980768
MAPE test: 0.09627228461440855

- **Данных немного, поэтому и скорость обучения высокая**
- **Регуляризация не улучшила точность -> мультиколлинеарность отсутствует**
- **Регуляризация с полиномиальными признаками и гипепараметром для Лассо немного улучшила точность -> существует некоторая нелинейная зависимость между данными**
- **В случае Лассо с гиперпараметром предсказания для train и test примерно одинаковой точности -> модель не запомнила много шума**
- **В случае Ridge с гиперпараметром предсказания для train и test разной точность (по r2: 0.96 и 0.87 соответсвенно) -> существуют лишние/коллинеарные признаки и произошло переобучение**

## Итого

1) Использованные метрики:
    - **MSE** - для оценки суммы обьективных отклонений (не MAE, т.к. он менее чувствителен к выбросам, которые критичны для данного датасета)
    - **MAPE** - для оценки ошибки в процентах (усредненной)
    - **R^2** - для оценки дисперсии нашей цены исходя из работы модели

2) На какой выборке метрики:
    - Также я считал метрики для тестовой и тренировочной выборок, чтобы оценить влияние шума и риски переобучения

3) Лучше по итогу справилась:
    - модель Лассо с гиперпараметром l = 30 для выборки с дополнительными полиномиальными признакакми - R^2 test: 0.92, MAPE test: 0.08. Почему лассо а не ridge - как видно из ridge, модель переобучилась - значит существуют лишние признаки, которые как раз были аннулированы регуляризацией Лассо, обнуляющей лишние признаки
    - Но также неплохо справилась модель без регуляризации и полиномиальных признаков - R^2: 0.905, MAPE: 0.085 - что говорит об отсутсвии коллизий в выборке данных

4) Насколько хорошие получились результаты:
    - В целом, меня они устроили, ибо точность довольно приемлимая (для средней цены по датасету 10730.8 модель предсказывает с точностью до 8-10% ~ +- 1000 евро (вроде евро)), однако единственное, что мне не особо нравится - большое число признаков, из-за чего регуляризация с полиномиальными признаками в случае с бОльшим числом данных сильно замедлится. С другой стороны, и без нее результат довольно точный, поэтому я в целом доволен этой работой

5) Чем докажете, что ваша модель не переобучилась?
    - Во всех случаях, кроме последнего (ridge с гиперпараметром) точность предсказантя модели почти не отличается на тренировочной и тестовой выборке, что говорит о том, что она не запомнила шум и не выучила тренировочный датасат, т.е. не переобучилась.